### ISSUE TITLE
Show npm errors

### ISSUE THREAD

**Issue by jvmlet** [jeysal/gradle-graphviz-plugin#1]
Hi
I'm getting below error when I run `vizSetup` task
```
Execution failed for task 'vizSetup'.
> Process 'command 'MyProjectRoot\.gradle\nodejs\node-v6.9.1-win-x64\npm.cmd'' finished with non-zero exit value 1
```

My gradle script :

```

buildscript {
    repositories {
        mavenCentral()
        maven {           url "https://plugins.gradle.org/m2/"        }
        maven { url 'https://jitpack.io' }

    }
    dependencies {
        classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.11'
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.4.12"
        classpath 'com.github.jeysal:gradle-graphviz-plugin:1.3.0'
    }
}
vizSetup.enabled = true
graphviz {
 // some settings
}
```

**Comment by jeysal** [comment]
Hi,
I didn't manage to reproduce this issue.
Could you try running vizSetup in a bare gradle project with just the basic configuration:
```groovy
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2' }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.github.jeysal:gradle-graphviz-plugin:1.3.0'
    }
}

apply plugin: 'com.github.jeysal.graphviz'
```

Also, are you running gradle in a special environment such as Cygwin or a Git Bash?

**Comment by jvmlet** [comment]
Hi, tried the bare gradle project - the same result.
My environment is gradlew on windows 7 (gradle-3.1), no Cygwin, no Bash.
I'm behind the firewall.
Would you please  add logs/npm command out/error file to debug the issue  to snapshot build?
Thanks

**Comment by jeysal** [comment]
Hi,

I've pushed 25108a6, which makes the npm install that is going on in the background non-silent if the build is run with `--debug`.
Using the latest snapshot you should be able to get some information about what went wrong from npm this way.
The reason why I silenced npm in the first place is to avoid its warnings that are completely irrelevant to users of the plugin.

**Comment by jvmlet** [comment]
Thanks @jeysal 

I think you've a bug in your latest commit trying to get the log level,
 Here is my `build.gradle`
```
buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven { url 'https://jitpack.io' }

    }
    dependencies {
        //classpath 'com.github.jeysal:gradle-graphviz-plugin:1.3.0'
        classpath 'com.github.jeysal:gradle-graphviz-plugin:master-SNAPSHOT'
    }
}
apply plugin: 'com.github.jeysal.graphviz'
println ("Log LEVEL :" + project.logging.level)
println("Log LEVEL is DEBUG :" + (project.logging.level == LogLevel.DEBUG))
```
I run it with `gradlew --debug  graphviz >> out.txt`

and this is what gets pronted :
```
08:10:09.388 [QUIET] [system.out] Log LEVEL :null
08:10:09.388 [QUIET] [system.out] Log LEVEL is DEBUG :false
```

Anyway, I run the command manually without the `--silent`, and the problem  is with proxy settings:

```
D:\DHP\asp_core\.gradle>D:\DHP\asp_core\test\.gradle\nodejs\node-v6.9.1-win-x64\npm.cmd install  viz.js-cli-wrapper@^1.3.0
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\DHP\\asp_core\\test\\.gradle\\nodejs\\node-v6.9.1-win-x64\\node.exe" "D:\\DHP\\asp_core\\test\\.gradle\\nodejs\\node-v6.9.1-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "
viz.js-cli-wrapper@1.3.0"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 9480 9480:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     D:\DHP\asp_core\.gradle\npm-debug.log
```

Do you expose the proxy settings in your plugin config or is it exposed via imported plugins ?

**Comment by jeysal** [comment]
The log level detection was indeed broken due to [weird behavior of Gradle](https://discuss.gradle.org/t/how-can-i-get-the-current-log-level/6768), I've adressed this in 696f264.
Thanks for reporting.

As for npm proxy settings, you can set up a config file in your user home directory as described [here](https://docs.npmjs.com/files/npmrc) and use the `proxy` and `https-proxy` settings (see [here](https://docs.npmjs.com/misc/config)) to configure the connection properly.

I've also added a npm troubleshooting section to the README for others who may have the same issue.

**Comment by jvmlet** [comment]
Thanks, I was able to configure the proxy, now getting below error when invoking  `graphviz` task :
`
graphviz command [D:\DHP\asp_core\pipeline\pipeline-initializer\.gradle\graphvizdot.cmd, -o, D:\DHP\asp_core\pipeline\pipeline-initializer\graphvizOut\graph.dot.png, D:\DHP\asp_core\pipeline\pipeline-initializer\graph.dot, -K, dot, -T, png] failed with exit code 2
`

My  `build.gradle` section :

```
vizSetup.enabled = true
graphviz {
    setGroup(JavaBasePlugin.DOCUMENTATION_GROUP)
   // dependsOn buildDiagramm
    /* Path of the Graphviz executable to use.
    If not set, viz provided by :vizSetup or Graphviz from PATH environment variable is used. */
    //executablePath = '/usr/bin/dot'

    // Graphviz layout engine to use. Defaults to the Graphviz executable's default layout (usually dot).
    layout = 'dot'

    /* Graphviz output formats to produce. Defaults to the Graphviz executable's default format (usually xdot).
    Note that if you specify a format twice or set formatSuffix to false,
    the formats overwrite each other and only the last one remains. */
    formats = ['png']

    /* If true, the chosen format will be appended to every output file name. Defaults to true.
    The default format will not be appended since Graphviz itself decides what to generate in that case. */
    //formatSuffix = false

    // Directory to scan for source files. Defaults to src/main/graphviz.
    //sourceDir = file('graphvizSrc')
    sourceDir = project.projectDir
    // Directory to generate Graphviz output into. Defaults to build/graphviz.
    outputDir = file('graphvizOut')

    /* Configures the sources to use via ant-style patterns.
    If not configured, sources default to the example below. */
    sources {
        include '**/*.gv', '**/*.dot'
    }
}
```

**Comment by jeysal** [comment]
Unfortunately, the `png` format is not supported. I've updated the README to point out the format limitations more clearly.

Supported formats at the moment are `svg`, `xdot`, `plain`, `ps` and `json`.
Depending on what you want to do with the generated graphs, `svg` may be useful instead of `png`.
